export const webRoutes = {
  home: '/',
  deposit: '/deposit',
  withdraw: '/withdraw',
  historyUser: '/history-user',
  tickets: '/tickets',
  login: '/login',
  logout: '/logout',
  dashboard: '/dashboard',
  pack: '/pack',
  users: '/users',
  setting: '/setting',
  codes: '/codes',
  about: '/about',
  userDetail: `/user-detail/:userId`,
};
